"""add_cascade_delete_constraints

Revision ID: 3c766b060c61
Revises: a9d874f8a711
Create Date: 2026-06-08 16:40:09.567512

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c766b060c61'
down_revision = 'a9d874f8a711'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    #op.drop_table('account')
    with op.batch_alter_table('category', schema=None) as batch_op:
       #batch_op.drop_constraint(batch_op.f('category_company_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key('fk_category_company', 'company', ['company_id'], ['company_id'], ondelete='CASCADE')

    with op.batch_alter_table('transaction', schema=None) as batch_op:
        pass
        #batch_op.drop_constraint(batch_op.f('transaction_account_id_fkey'), type_='foreignkey')
        #batch_op.drop_column('account_id')

    with op.batch_alter_table('user_company', schema=None) as batch_op:
        # batch_op.drop_constraint(batch_op.f('user_company_company_id_fkey'), type_='foreignkey')
        # batch_op.drop_constraint(batch_op.f('user_company_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key('fk_user_company_user', 'user', ['user_id'], ['user_id'], ondelete='CASCADE')
        batch_op.create_foreign_key('fk_user_company_company', 'company', ['company_id'], ['company_id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_company', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('user_company_user_id_fkey'), 'user', ['user_id'], ['user_id'])
        batch_op.create_foreign_key(batch_op.f('user_company_company_id_fkey'), 'company', ['company_id'], ['company_id'])

    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('account_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('transaction_account_id_fkey'), 'account', ['account_id'], ['account_id'], ondelete='SET NULL')

    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('category_company_id_fkey'), 'company', ['company_id'], ['company_id'])

    op.create_table('account',
    sa.Column('account_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('value', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('due_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('payment_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('created_at', sa.DATE(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['category.category_id'], name=op.f('account_category_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['company_id'], ['company.company_id'], name=op.f('account_company_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('account_id', name=op.f('account_pkey'))
    )
    # ### end Alembic commands ###
