"""cria tabela de documentos com FK e cascade delete

Revision ID: 64ce364b8362
Revises: a9d874f8a711
Create Date: 2026-06-05 20:41:30.444988

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64ce364b8362'
down_revision = 'a9d874f8a711'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bill',
    sa.Column('bill_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('type', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.category_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['company_id'], ['company.company_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('bill_id')
    )
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('bill_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint(batch_op.f('transaction_category_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'bill', ['bill_id'], ['bill_id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'category', ['category_id'], ['category_id'], ondelete='RESTRICT')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'company', ['company_id'], ['company_id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('company_id')

    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('transaction_category_id_fkey'), 'category', ['category_id'], ['category_id'], ondelete='CASCADE')
        batch_op.drop_column('bill_id')
        batch_op.drop_column('created_at')

    op.drop_table('bill')
    # ### end Alembic commands ###
