"""atualiza relacionamentos de account nos models

Revision ID: 6f1ba7b629be
Revises: 98d908e76b36
Create Date: 2026-06-08 15:22:21.171670

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f1ba7b629be'
down_revision = '98d908e76b36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.alter_column('value',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=False)

    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('transaction_account_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'account', ['account_id'], ['account_id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('transaction_account_id_fkey'), 'account', ['account_id'], ['account_id'])

    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.alter_column('value',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)

    # ### end Alembic commands ###
