"""fix: adiciona campo is_active no model User

Revision ID: 72852b4102c3
Revises: 0d1cc55554da
Create Date: 2026-06-25 21:21:17.690852

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72852b4102c3'
down_revision = '0d1cc55554da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comparison',
    sa.Column('comparison_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('loan_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.company_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('comparison_id')
    )
    op.create_table('simulation',
    sa.Column('simulation_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('valor_solicitado', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('prazo_meses', sa.Integer(), nullable=False),
    sa.Column('modalidade', sa.String(length=10), nullable=False),
    sa.Column('taxa_juros', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('valor_parcela', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('valor_total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_juros', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('data_simulacao', sa.DateTime(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.company_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('simulation_id')
    )
    op.create_table('comparison_modality',
    sa.Column('modality_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('comparison_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('interest_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('term_months', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=10), nullable=False),
    sa.Column('monthly_payment', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_interest', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['comparison_id'], ['comparison.comparison_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('modality_id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    op.drop_table('comparison_modality')
    op.drop_table('simulation')
    op.drop_table('comparison')
    # ### end Alembic commands ###
