"""add many-to-many relationship between user and company

Revision ID: a1116d4d7ff8
Revises: 2a5aec4b61c2
Create Date: 2026-05-23 11:11:39.610159

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1116d4d7ff8'
down_revision = '2a5aec4b61c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cpf', sa.String(length=11), nullable=False))
        batch_op.create_unique_constraint('uq_user_email', ['cpf'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('cpf')

    # ### end Alembic commands ###
