"""refactor: migra estrutura de Account para Bill e atualiza relacionamentos

Revision ID: d7a779e5f5b4
Revises: a9d874f8a711
Create Date: 2026-06-08 15:53:09.063551

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7a779e5f5b4'
down_revision = 'a9d874f8a711'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('account')
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('transaction_account_id_fkey'), type_='foreignkey')
        batch_op.drop_column('account_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('account_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('transaction_account_id_fkey'), 'account', ['account_id'], ['account_id'], ondelete='SET NULL')

    op.create_table('account',
    sa.Column('account_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('value', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('due_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('payment_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('created_at', sa.DATE(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['category.category_id'], name=op.f('account_category_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['company_id'], ['company.company_id'], name=op.f('account_company_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('account_id', name=op.f('account_pkey'))
    )
    # ### end Alembic commands ###
